name: release

on:
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - name: Install svu
        run: |
          echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | sudo tee /etc/apt/sources.list.d/caarlos0.list
          sudo apt update
          sudo apt install svu

      # check if we need to bump
      - name: check for release
        run: |
          echo svu next: $(svu next)
          echo svu current $(svu current)
          if [ $(svu next) == $(svu current) ]; then
            echo "tag match"
          else
            echo "tag mismatch"
          fi
          echo "skip-release=true" >> $GITHUB_ENV

      - name: Tag new version
        if: ${{ env.skip-release == 'false' }}
        run: |
          echo ${{ env.skip }}
          git tag $(svu next)
          git push --tags

      # only run if commit msg is correct
      - name: check for release
        if: ${{ env.skip-release == 'false' }}
        run: |
          echo deploying....
